// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutTest2IndexImport } from './routes/_layout/test2/index'
import { Route as LayoutTestIndexImport } from './routes/_layout/test/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutTest2IndexRoute = LayoutTest2IndexImport.update({
  path: '/test2/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTestIndexRoute = LayoutTestIndexImport.update({
  path: '/test/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/test/': {
      preLoaderRoute: typeof LayoutTestIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/test2/': {
      preLoaderRoute: typeof LayoutTest2IndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([LayoutTestIndexRoute, LayoutTest2IndexRoute]),
])
